application: practica1
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: practica1.application

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
    #Pasos para ejecutar
    #cd ..
    #dev_appserver.py Practica1/
    #localhost:8080


